import { deleteCompany } from "@/app/actions";
import { ConfirmButton } from "@/components/confirm-button";
import { Card, EmptyState, PageHeader, dangerButton, primaryButton, secondaryButton } from "@/components/ui";
import { formatDate } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { getCompanyStatement, normalizeStatementFilters, statementQueryString } from "@/lib/statement";
import { Download, Edit3, FilePlus2, FileText, WalletCards } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";

export default async function CompanyDetail({ params, searchParams }: { params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>> }) {
  const [{id:rawId},query]=await Promise.all([params,searchParams]);const id=Number(rawId);const filters=normalizeStatementFilters(query);const statement=await getCompanyStatement(id,filters);if(!statement)notFound();const {company,summary,rows}=statement;const exportQuery=statementQueryString(filters);const suffix=exportQuery?`?${exportQuery}`:"";
  return <><PageHeader title={company.name} description={[company.email,company.phone].filter(Boolean).join(" · ")||"Company account"} action={<div className="flex flex-wrap gap-2"><Link href={`/received-money?company=${id}`} className={secondaryButton}><WalletCards size={16}/>Add receipt</Link><Link href={`/invoices/new?company=${id}`} className={primaryButton}><FilePlus2 size={16}/>New invoice</Link><Link href={`/companies/${id}/edit`} className={secondaryButton}><Edit3 size={16}/>Edit</Link></div>}/>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary label="Opening balance" value={formatMoney(summary.openingBalance)}/><Summary label="Received in period" value={formatMoney(summary.totalReceived)} accent="green"/><Summary label="Final invoices" value={formatMoney(summary.totalFinalInvoices)}/><Summary label="Cancelled invoices" value={formatMoney(summary.totalCancelledInvoices)} accent="red"/><Summary label="Closing balance" value={formatMoney(summary.closingBalance)} accent={summary.closingBalance<0?"red":"green"}/></div>
    <Card className="mt-6 p-5"><form method="get" className="grid gap-4 md:grid-cols-2 xl:grid-cols-6"><div><label htmlFor="from">From date</label><input id="from" name="from" type="date" defaultValue={filters.from}/></div><div><label htmlFor="to">To date</label><input id="to" name="to" type="date" defaultValue={filters.to}/></div><div><label htmlFor="type">Transaction type</label><select id="type" name="type" defaultValue={filters.type}><option value="ALL">All</option><option value="PAYMENTS">Payments</option><option value="INVOICES">Invoices</option></select></div><div><label htmlFor="status">Invoice status</label><select id="status" name="status" defaultValue={filters.status}><option value="ALL">All</option><option value="FINAL">Final</option><option value="CANCELLED">Cancelled</option><option value="DRAFT">Draft</option></select></div><div className="xl:col-span-2"><label htmlFor="search">Reference search</label><input id="search" name="search" defaultValue={filters.search} placeholder="Invoice or payment reference"/></div><label className="mb-0 flex items-center gap-2 text-sm xl:col-span-2"><input className="h-4 w-4" type="checkbox" name="showDrafts" value="1" defaultChecked={filters.showDrafts}/>Show draft invoices</label><div className="flex gap-2 xl:col-span-4 xl:justify-end"><Link href={`/companies/${id}`} className={secondaryButton}>Reset</Link><button className={primaryButton}>Apply filters</button></div></form></Card>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Statement ledger</h2><p className="mt-1 text-xs text-slate-500">Running balance uses payments and Final invoices only. Cancelled and Draft rows have no balance effect.</p></div><div className="flex flex-wrap gap-2"><a href={`/api/companies/${id}/statement.csv${suffix}`} className={secondaryButton}><Download size={16}/>Export Statement CSV</a><a href={`/api/companies/${id}/statement.pdf${suffix}`} className={primaryButton}><FileText size={16}/>Download Statement PDF</a></div></div>
    <Card className="mt-4 overflow-hidden">{rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Description</th><th className="px-4 py-3 text-right">Debit</th><th className="px-4 py-3 text-right">Credit</th><th className="px-4 py-3 text-right">Running Balance</th></tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.key} className={row.status==="Cancelled"?"bg-red-50/50 text-slate-500":row.status==="Draft"?"bg-amber-50/50 text-slate-600":"hover:bg-slate-50"}><td className="whitespace-nowrap px-4 py-3">{formatDate(row.date)}</td><td className="px-4 py-3 font-medium">{row.type}</td><td className="px-4 py-3 font-medium">{row.reference}</td><td className="px-4 py-3"><Status status={row.status}/></td><td className="max-w-xs truncate px-4 py-3 text-slate-500">{row.description}</td><td className={`px-4 py-3 text-right ${row.status==="Cancelled"||row.status==="Draft"?"line-through":""}`}>{row.debit==null?"—":formatMoney(row.debit)}</td><td className="px-4 py-3 text-right text-brand-700">{row.credit==null?"—":formatMoney(row.credit)}</td><td className="px-4 py-3 text-right font-semibold">{formatMoney(row.runningBalance)}</td></tr>)}</tbody></table></div>:<EmptyState>No statement transactions match the selected filters.</EmptyState>}</Card>
    {(company.address)&&<Card className="mt-5 p-5 text-sm text-slate-600"><strong className="text-slate-800">Company address</strong><p className="mt-1 whitespace-pre-line">{company.address}</p></Card>}
    <form action={deleteCompany} className="mt-6"><input type="hidden" name="id" value={id}/><ConfirmButton className={dangerButton} message="Delete this company? Companies with invoices cannot be deleted.">Delete company</ConfirmButton></form>
  </>;
}
function Summary({label,value,accent}:{label:string;value:string;accent?:"green"|"red"}){return <Card className="p-4"><div className="text-xs text-slate-500">{label}</div><div className={`mt-2 text-lg font-semibold ${accent==="green"?"text-brand-700":accent==="red"?"text-red-600":""}`}>{value}</div></Card>}
function Status({status}:{status:"Received"|"Final"|"Cancelled"|"Draft"}){const style=status==="Received"||status==="Final"?"bg-brand-50 text-brand-700":status==="Cancelled"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${style}`}>{status}</span>}
