import { AnalyticsRangeFilter } from "@/components/analytics-range-filter";
import { Card, EmptyState, PageHeader } from "@/components/ui";
import { getBusinessAnalytics, normalizeAnalyticsFilters } from "@/lib/analytics";
import { formatDate } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import Link from "next/link";

export const dynamic="force-dynamic";
export default async function AnalyticsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const filters=normalizeAnalyticsFilters(await searchParams);const data=await getBusinessAnalytics(filters);const maxBalance=Math.max(1,...data.companyBalances.map(c=>Math.abs(c.balance)));const maxMonthly=Math.max(1,...data.monthly.flatMap(m=>[m.received,m.invoiced]));return <>
  <PageHeader title="Analytics" description={`Official performance analytics for ${filters.label}. Draft and Cancelled invoices are excluded from financial totals.`}/><AnalyticsRangeFilter filters={filters}/>
  <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Mini label="Final invoices" value={formatMoney(data.metrics.totalFinalInvoiced)} note="Official invoice value in period"/><Mini label="Draft invoices" value={String(data.metrics.draftCount)} note="Visible count; excluded from totals" tone="amber"/><Mini label="Cancelled invoices" value={String(data.metrics.cancelledCount)} note={`${formatMoney(data.metrics.cancelledValue)} excluded`} tone="red"/><Mini label="Money in hand" value={formatMoney(data.metrics.moneyInHand)} note={`Official balance as of ${filters.to}`} tone={data.metrics.moneyInHand<0?"red":"green"}/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="p-5"><SectionTitle title="Monthly received vs Final invoiced" note="Only received payments and Final invoices are included."/>{data.monthly.length?<div className="mt-6 space-y-5">{data.monthly.map(row=><div key={row.month}><div className="mb-2 text-xs font-semibold text-slate-600">{monthLabel(row.month)}</div><ChartBar label="Received" value={row.received} max={maxMonthly} color="bg-brand-500"/><ChartBar label="Final invoiced" value={row.invoiced} max={maxMonthly} color="bg-slate-500"/></div>)}</div>:<EmptyState>No official activity in this period.</EmptyState>}</Card>
  <Card className="p-5"><SectionTitle title="Money in hand by company" note={`Balances as of ${filters.to}. Negative values are highlighted.`}/>{data.companyBalances.length?<div className="mt-6 space-y-4">{[...data.companyBalances].sort((a,b)=>b.balance-a.balance).map(c=><div key={c.id}><div className="mb-1.5 flex justify-between gap-3 text-xs"><Link href={`/companies/${c.id}`} className="font-semibold hover:text-brand-700">{c.name}</Link><span className={c.balance<0?"font-semibold text-red-600":"font-semibold text-brand-700"}>{formatMoney(c.balance)}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${c.balance<0?"bg-red-500":"bg-brand-500"}`} style={{width:`${Math.max(1,Math.abs(c.balance)/maxBalance*100)}%`}}/></div></div>)}</div>:<EmptyState>No company balances yet.</EmptyState>}</Card></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><CompanyReport title="Negative balance companies" note="Companies whose Final invoices exceed received payments." rows={data.negativeCompanies} empty="No negative balances."/><CompanyReport title="High balance companies" note="Largest positive money-in-hand balances." rows={data.highBalanceCompanies} empty="No positive balances."/><Card><div className="border-b px-5 py-4"><SectionTitle title="Inactive for 30+ days" note={`No activity since before ${new Date(filters.end.getTime()-30*86_400_000).toISOString().slice(0,10)}.`}/></div>{data.inactiveCompanies.length?<div className="divide-y">{data.inactiveCompanies.slice(0,10).map(c=><Link href={`/companies/${c.id}`} key={c.id} className="flex items-center justify-between px-5 py-3 hover:bg-slate-50"><span className="text-sm font-medium">{c.name}</span><span className="text-xs text-slate-500">{c.lastActivity?formatDate(c.lastActivity):"Never active"}</span></Link>)}</div>:<EmptyState>Every company was active in the last 30 days.</EmptyState>}</Card></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><Ranked title="Top items by quantity" note="Item quantities on Final invoices in period." rows={data.topItemsByQuantity.map(r=>({label:r.name,value:String(r.quantity),sub:formatMoney(r.value)}))}/><Ranked title="Top items by total value" note="Line totals on Final invoices in period." rows={data.topItemsByValue.map(r=>({label:r.name,value:formatMoney(r.value),sub:`${r.quantity} units`}))}/><Ranked title="Top companies by invoice value" note="Final invoice grand totals in period." rows={data.topCompaniesByInvoice.map(r=>({label:r.name,value:formatMoney(r.value),href:`/companies/${r.id}`}))}/><Ranked title="Top companies by received amount" note="Received payments in period." rows={data.topCompaniesByReceived.map(r=>({label:r.name,value:formatMoney(r.value),href:`/companies/${r.id}`}))}/></div>
  <Card className="mt-6"><div className="border-b px-5 py-4"><SectionTitle title="Monthly charges" note="Commission, packing, and transportation on Final invoices only."/></div>{data.monthly.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="border-b bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Month</th><th className="px-5 py-3 text-right">Commission</th><th className="px-5 py-3 text-right">Packing</th><th className="px-5 py-3 text-right">Transportation</th><th className="px-5 py-3 text-right">Total charges</th></tr></thead><tbody className="divide-y">{data.monthly.map(row=><tr key={row.month}><td className="px-5 py-4 font-medium">{monthLabel(row.month)}</td><td className="px-5 py-4 text-right">{formatMoney(row.commission)}</td><td className="px-5 py-4 text-right">{formatMoney(row.packing)}</td><td className="px-5 py-4 text-right">{formatMoney(row.transportation)}</td><td className="px-5 py-4 text-right font-semibold">{formatMoney(row.commission+row.packing+row.transportation)}</td></tr>)}</tbody></table></div>:<EmptyState>No Final invoice charges in this period.</EmptyState>}</Card>
  </>}
function SectionTitle({title,note}:{title:string;note:string}){return <div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{note}</p></div>}
function Mini({label,value,note,tone="slate"}:{label:string;value:string;note:string;tone?:"slate"|"green"|"red"|"amber"}){const cls=tone==="green"?"text-brand-700":tone==="red"?"text-red-600":tone==="amber"?"text-amber-700":"";return <Card className="p-5"><p className="text-xs font-medium text-slate-500">{label}</p><p className={`mt-2 text-2xl font-semibold ${cls}`}>{value}</p><p className="mt-2 text-[11px] text-slate-400">{note}</p></Card>}
function ChartBar({label,value,max,color}:{label:string;value:number;max:number;color:string}){return <div className="mb-2 grid grid-cols-[85px_1fr_auto] items-center gap-3 text-xs"><span className="text-slate-500">{label}</span><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{width:`${Math.max(value?2:0,value/max*100)}%`}}/></div><span className="min-w-24 text-right font-medium">{formatMoney(value)}</span></div>}
function CompanyReport({title,note,rows,empty}:{title:string;note:string;rows:{id:number;name:string;balance:number}[];empty:string}){return <Card><div className="border-b px-5 py-4"><SectionTitle title={title} note={note}/></div>{rows.length?<div className="divide-y">{rows.slice(0,10).map(c=><Link href={`/companies/${c.id}`} key={c.id} className="flex justify-between gap-3 px-5 py-3 text-sm hover:bg-slate-50"><span className="font-medium">{c.name}</span><span className={c.balance<0?"font-semibold text-red-600":"font-semibold text-brand-700"}>{formatMoney(c.balance)}</span></Link>)}</div>:<EmptyState>{empty}</EmptyState>}</Card>}
function Ranked({title,note,rows}:{title:string;note:string;rows:{label:string;value:string;sub?:string;href?:string}[]}){return <Card><div className="border-b px-5 py-4"><SectionTitle title={title} note={note}/></div>{rows.length?<ol className="divide-y">{rows.map((row,index)=><li key={`${row.label}-${index}`} className="flex items-center gap-4 px-5 py-3"><span className="grid h-7 w-7 place-items-center rounded-lg bg-slate-100 text-xs font-semibold text-slate-500">{index+1}</span><div className="min-w-0 flex-1">{row.href?<Link href={row.href} className="truncate text-sm font-medium hover:text-brand-700">{row.label}</Link>:<div className="truncate text-sm font-medium">{row.label}</div>}{row.sub&&<div className="text-xs text-slate-500">{row.sub}</div>}</div><span className="text-sm font-semibold">{row.value}</span></li>)}</ol>:<EmptyState>No Final invoice data in this period.</EmptyState>}</Card>}
function monthLabel(value:string){return new Intl.DateTimeFormat("en-AE",{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}-01T00:00:00Z`))}
