"use server";

import { db } from "@/lib/db";
import { clearCurrentSession, establishSession, getCurrentSession, requireSession } from "@/lib/auth";
import { hashPassword, validatePassword, verifyPassword } from "@/lib/password";
import { writeAuditLog } from "@/lib/audit";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";

export type AuthFormState={error?:string};
const text=(formData:FormData,key:string)=>String(formData.get(key)??"");
const confirmedPassword=(formData:FormData)=>{const password=text(formData,"password"),confirmation=text(formData,"confirmation");const error=validatePassword(password);if(error)throw new Error(error);if(password!==confirmation)throw new Error("Password confirmation does not match.");return password};

export async function setupPasswordAction(_state:AuthFormState,formData:FormData):Promise<AuthFormState>{try{if(await db.localAuth.findUnique({where:{id:1}}))return{error:"Password protection is already configured."};const password=confirmedPassword(formData);const passwordHash=await hashPassword(password);const auth=await db.localAuth.create({data:{id:1,passwordHash,sessionTimeoutMinutes:60}});await writeAuditLog({action:"PASSWORD_SETUP",entityType:"Security",entityReference:"local-user",details:"Local password protection configured"});await establishSession(auth.id,auth.sessionTimeoutMinutes)}catch(error){return{error:error instanceof Error?error.message:"Could not configure password protection."}}redirect("/")}
export async function loginAction(_state:AuthFormState,formData:FormData):Promise<AuthFormState>{const auth=await db.localAuth.findUnique({where:{id:1}});if(!auth)redirect("/setup");const now=new Date();if(auth.lockedUntil&&auth.lockedUntil>now)return{error:`Too many attempts. Try again after ${auth.lockedUntil.toLocaleTimeString("en-AE")}.`};const valid=await verifyPassword(text(formData,"password"),auth.passwordHash);if(!valid){const attempts=auth.failedLoginAttempts+1;await db.localAuth.update({where:{id:auth.id},data:{failedLoginAttempts:attempts>=5?0:attempts,lockedUntil:attempts>=5?new Date(now.getTime()+5*60_000):null}});return{error:"Incorrect password."}}await db.localAuth.update({where:{id:auth.id},data:{failedLoginAttempts:0,lockedUntil:null}});await establishSession(auth.id,auth.sessionTimeoutMinutes);redirect("/")}
export async function logoutAction(){await clearCurrentSession();redirect("/login")}
export async function changePasswordAction(_state:AuthFormState,formData:FormData):Promise<AuthFormState>{try{const session=await requireSession();const current=text(formData,"currentPassword");if(!await verifyPassword(current,session.auth.passwordHash))return{error:"Current password is incorrect."};const password=confirmedPassword(formData);const passwordHash=await hashPassword(password);await db.$transaction([db.localAuth.update({where:{id:session.authId},data:{passwordHash,failedLoginAttempts:0,lockedUntil:null}}),db.authSession.deleteMany({where:{authId:session.authId}}),db.auditLog.create({data:{action:"PASSWORD_CHANGED",entityType:"Security",entityReference:"local-user",details:"Local password changed and previous sessions revoked"}})]);await establishSession(session.authId,session.auth.sessionTimeoutMinutes)}catch(error){return{error:error instanceof Error?error.message:"Could not change password."}}redirect("/settings?security=password-changed")}
export async function updateSessionTimeoutAction(formData:FormData){const session=await requireSession();const minutes=Number(formData.get("sessionTimeoutMinutes"));if(!Number.isInteger(minutes)||![15,30,60,240,480,1440].includes(minutes))throw new Error("Invalid session timeout.");await db.localAuth.update({where:{id:session.authId},data:{sessionTimeoutMinutes:minutes}});await writeAuditLog({action:"SESSION_TIMEOUT_UPDATED",entityType:"Security",entityReference:"local-user",details:{minutes}});revalidatePath("/settings");redirect("/settings?security=timeout-saved")}
